export const columns = [
  {
    name: "name",
    required: true,
    label: "Concepto",
    align: "left",
    field: (row) => row.name,
    format: (val) => `${val}`,
    sortable: true,
    classes: " ellipsis",
    style: "max-width: 200px",
    headerClasses: "bg-primary text-white",
    headerStyle: "max-width: 200px",
  },
  {
    name: "calories",
    align: "center",
    label: "Cantidad",
    field: "calories",
    sortable: true,
    classes: " ellipsis",
    style: "max-width: 80px",
    headerClasses: "bg-primary text-white",
    headerStyle: "max-width: 80px",
  },
  {
    name: "fat",
    label: "Unidad",
    field: "fat",
    sortable: true,
    classes: " ellipsis",
    style: "max-width: 80px",
    headerClasses: "bg-primary text-white",
    headerStyle: "max-width: 80px",
  },
  {
    name: "carbs",
    label: "Clave SAT",
    field: "carbs",
    classes: " ellipsis",
    style: "max-width: 150px",
    headerClasses: "bg-primary text-white",
    headerStyle: "max-width: 1500px",
  },
  {
    name: "protein",
    label: "Unitario",
    field: "protein",
    classes: " ellipsis",
    style: "max-width: 80px",
    headerClasses: "bg-primary text-white",
    headerStyle: "max-width: 80px",
  },
  {
    name: "sodium",
    label: "Impuesto",
    field: "sodium",
    classes: "ellipsis",
    style: "max-width: 80px",
    headerClasses: "bg-primary text-white",
    headerStyle: "max-width: 80px",
  },
  {
    name: "calcium",
    label: "Importe",
    field: "calcium",
    sortable: true,
    sort: (a, b) => parseInt(a, 10) - parseInt(b, 10),
    classes: " ellipsis",
    style: "max-width: 1500px",
    headerClasses: "bg-primary text-white",
    headerStyle: "max-width: 1500px",
  },
];

export const rows = [
  {
    name: "Licencia de Contpaqi para NOMINAS, supervision de equipos y telecominicaciones",
    calories: 159,
    fat: 6.0,
    carbs: 24,
    protein: 4.0,
    sodium: 87,
    calcium: "14%",
    iron: "1%",
  },
  {
    name: "Ice cream sandwich",
    calories: 237,
    fat: 9.0,
    carbs: 37,
    protein: 4.3,
    sodium: 129,
    calcium: "8%",
    iron: "1%",
  },
  {
    name: "Eclair",
    calories: 262,
    fat: 16.0,
    carbs: 23,
    protein: 6.0,
    sodium: 337,
    calcium: "6%",
    iron: "7%",
  },
  {
    name: "Cupcake",
    calories: 305,
    fat: 3.7,
    carbs: 67,
    protein: 4.3,
    sodium: 413,
    calcium: "3%",
    iron: "8%",
  },
  {
    name: "Gingerbread",
    calories: 356,
    fat: 16.0,
    carbs: 49,
    protein: 3.9,
    sodium: 327,
    calcium: "7%",
    iron: "16%",
  },
  {
    name: "Jelly bean",
    calories: 375,
    fat: 0.0,
    carbs: 94,
    protein: 0.0,
    sodium: 50,
    calcium: "0%",
    iron: "0%",
  },
  {
    name: "Lollipop",
    calories: 392,
    fat: 0.2,
    carbs: 98,
    protein: 0,
    sodium: 38,
    calcium: "0%",
    iron: "2%",
  },
  {
    name: "Honeycomb",
    calories: 408,
    fat: 3.2,
    carbs: 87,
    protein: 6.5,
    sodium: 562,
    calcium: "0%",
    iron: "45%",
  },
  {
    name: "Donut",
    calories: 452,
    fat: 25.0,
    carbs: 51,
    protein: 4.9,
    sodium: 326,
    calcium: "2%",
    iron: "22%",
  },
  {
    name: "KitKat",
    calories: 518,
    fat: 26.0,
    carbs: 65,
    protein: 7,
    sodium: 54,
    calcium: "12%",
    iron: "6%",
  },
];
